# Generated by Django 4.1.7 on 2023-04-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enviroment',
            old_name='house_id',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='enviroment',
            old_name='regoster_date',
            new_name='register_date',
        ),
        migrations.RenameField(
            model_name='enviroment',
            old_name='renter_id',
            new_name='renter',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='Enviroment',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='enviroment_id',
            new_name='enviroment',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='service_id',
            new_name='service',
        ),
    ]
