# Generated by Django 4.1.7 on 2023-04-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0002_rename_house_id_enviroment_house_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enviroment',
            old_name='regoster_date',
            new_name='register_date',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='Enviroment',
            new_name='district',
        ),
    ]
